
var data = [  
        {
    logo:'./image/apple_logo.jpg'
    type:'electronics'
    name:'Apple'
    },
        {
    logo:'./image/att_logo.jpg'
    type:'service'
    name:'AT&T'
    },
        {
    logo:'./image/./image/./image/bmw_logo.jpg'
    type:'cars'
    name:'BMW'
    },
        {
    logo:'./image/./image/mercedes_benz_logo.jpg'
    type:'cars'
    name:'Mercedes Benz'
    },
        {
    logo:'./image/./image/nike_logo.jpg'
    type:'clothes'
    name:'Nike'
    },
        {
    logo:'./image/./image/porsche_logo.jpg'
    type:'cars'
    name:'Porsche'
    },
        {
    logo:'./image/./image/nissan_logo.jpg'
    type:'cars'
    name:'Nissan'
    },
        {
    logo:'./image/mcdonalds_logo.jpg'
    type:'food'
    name:'McDonalds'
    },
        {
    logo:'./image/microsoft_logo.png'
    type:'electronics'
    name:'Microsoft'
    },
        {
    logo:'./image/honda_logo.jpg'
    type:'cars'
    name:'Honda'
    },
        {
    logo:'./image/comcast_logo.jpg'
    type:'tv'
    name:'Comcast'
    },
        {
    logo:'./image/directv_logo.jpg'
    type:'tv'
    name:'Direct TV'
    },
        {
    logo:'./image/cvs_logo.png'
    type:'retail'
    name:'CVS'
    },
        {
    logo:'./image/walgreens_logo.jpg'
    type:'retail'
    name:'Walgreens'
    },
        {
    logo:'./image/hyundai_logo.jpg'
    type:'cars'
    name:'Hyundai'
    },
        {
    logo:'./image/sony_logo.jpg'
    type:'electronics'
    name:'Sony'
    },
        {
    logo:'./image/samsung_logo.jpg'
    type:'electronics'
    name:'Samsung'
    },
        {
    logo:'./image/capital_one_logo.jpg'
    type:'bank'
    name:'Capital One'
    },
        {
    logo:'./image/chase_logo.jpg'
    type:'bank'
    name:'Chase'
    },
        {
    logo:'./image/citi_logo.jpg'
    type:'bank'
    name:'CitiBank'
    },
        {
    logo:'./image/exxonmobil_logo.jpg'
    type:'gas'
    name:'Exxon Mobil'
    },
        {
    logo:'./image/toyota_logo.jpg'
    type:'cars'
    name:'Toyota'
    },
        {
    logo:'./image/walmart_logo.jpg'
    type:'retail'
    name:'Walmart'
    },
        {
    logo:'./image/verizon_logo.jpg'
    type:'service'
    name:'Verizon'
    },
        {
    logo:'./image/wells_fargo_logo.jpg'
    type:'bank'
    name:'Wells Fargo'
    },
        {
    logo:'./image/shell_logo.jpg'
    type:'gas'
    name:'Shell'
    },
        {
    logo:'./image/sam_s_club_logo.jpg'
    type:'wholesale'
    name:'Sams Club'
    },
        {
    logo:'./image/costco_logo.jpg'
    type:'wholesale'
    name:'Costco'
    },
        {
    logo:'./image/h_m_logo.jpg'
    type:'clothes'
    name:'H&M'
    },
        {
    logo:'./image/bp_logo.jpg'
    type:'gas'
    name:'BP'
    },
        {
    logo:'./image/subway_logo.jpg'
    type:'food'
    name:'Subway'
    },
];